#!/usr/bin/env python3
"""Compare backend outputs and compute RMSE convergence metrics.

Renders each example through matplotlib, Vega (vl-convert), and fortplot
in both MPL and Vega-Lite modes, then computes pixel-level RMSE between
the reference and fortplot outputs.

Usage:
    python scripts/compare_backends.py [--threshold 15.0]

Exit code is non-zero when any RMSE exceeds the threshold.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    example_root = repo_root / "examples" / "python"
    output_root = repo_root / "build" / "compare"
    output_root.mkdir(parents=True, exist_ok=True)

    require_tools()

    results: list[dict[str, Any]] = []
    for script in sorted(example_root.glob("*/*.py")):
        slug = script.parent.name
        out_dir = output_root / slug
        out_dir.mkdir(parents=True, exist_ok=True)
        row = compare_example(repo_root, script, out_dir)
        if row:
            results.append(row)

    print_table(results)
    check_threshold(results, args.threshold)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--threshold", type=float, default=15.0,
        help="Maximum acceptable RMSE (default: 15.0).",
    )
    return parser.parse_args()


def require_tools() -> None:
    try:
        import vl_convert  # noqa: F401
    except ImportError:
        print("vl-convert-python is required: pip install vl-convert-python", file=sys.stderr)
        sys.exit(1)
    try:
        from PIL import Image  # noqa: F401
    except ImportError:
        print("Pillow is required: pip install Pillow", file=sys.stderr)
        sys.exit(1)
    from mplvega.fortplot import find_render_executable
    if find_render_executable() is None:
        print("fortplot_render not found", file=sys.stderr)
        sys.exit(1)


def compare_example(
    repo_root: Path, script: Path, out_dir: Path
) -> dict[str, Any] | None:
    slug = script.parent.name

    # Generate MPL reference PNG
    mpl_png = out_dir / "ref_mpl.png"
    run_example(repo_root, script, out_dir, backend="mpl", mpl_exts=("png",))
    mpl_candidates = list(out_dir.glob("*.mpl.png"))
    if mpl_candidates:
        mpl_png = mpl_candidates[0]

    # Generate mplvega JSON (MPL mode)
    run_example(repo_root, script, out_dir, backend="mplvega", variants=("json", "fortplot"))
    json_candidates = list(out_dir.glob("*.vl.json"))
    if not json_candidates:
        return None
    spec_path = json_candidates[0]
    stem = spec_path.name[:-8]

    # Render Vega PNG from JSON
    vega_png = out_dir / f"{stem}.vega.png"
    render_vega_png(spec_path, vega_png)

    # fortplot MPL-mode PNG (already generated by example run)
    fortplot_mpl_png = out_dir / f"{stem}.png"

    # fortplot Vega-mode PNG
    fortplot_vega_png = out_dir / f"{stem}.vega_style.png"
    render_fortplot(spec_path, fortplot_vega_png, style="vegalite")

    row: dict[str, Any] = {"example": slug}

    if mpl_png.exists() and fortplot_mpl_png.exists():
        row["mpl_vs_fortplot_mpl"] = compute_rmse(mpl_png, fortplot_mpl_png)
    else:
        row["mpl_vs_fortplot_mpl"] = None

    if vega_png.exists() and fortplot_vega_png.exists():
        row["vega_vs_fortplot_vega"] = compute_rmse(vega_png, fortplot_vega_png)
    else:
        row["vega_vs_fortplot_vega"] = None

    return row


def run_example(
    repo_root: Path,
    script: Path,
    out_dir: Path,
    backend: str = "mplvega",
    variants: tuple[str, ...] = (),
    mpl_exts: tuple[str, ...] = (),
) -> None:
    env = os.environ.copy()
    pythonpath = str(repo_root / "src")
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = pythonpath if not existing else f"{pythonpath}{os.pathsep}{existing}"
    env["MPLVEGA_EXAMPLE_BACKEND"] = backend

    command = [sys.executable, str(script), "--outdir", str(out_dir), "--backend", backend]
    for v in variants:
        command.extend(["--variant", v])
    for ext in mpl_exts:
        command.extend(["--mpl-ext", ext])

    try:
        subprocess.run(command, cwd=repo_root, env=env, check=True,
                        capture_output=True, timeout=60)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        print(f"  warning: {script.parent.name} failed ({exc})", file=sys.stderr)


def render_vega_png(spec_path: Path, output: Path) -> None:
    import vl_convert as vlc
    from mplvega._state import _browser_spec

    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    png_bytes = vlc.vegalite_to_png(_browser_spec(spec), scale=1)
    output.write_bytes(png_bytes)


def render_fortplot(spec_path: Path, output: Path, style: str = "mpl") -> None:
    from mplvega.fortplot import find_render_executable

    renderer = find_render_executable()
    if renderer is None:
        return
    payload = spec_path.read_text(encoding="utf-8")
    subprocess.run(
        [renderer, "--style", style, "-o", str(output)],
        input=payload, capture_output=True, text=True, timeout=30, check=False,
    )


def compute_rmse(path_a: Path, path_b: Path) -> float:
    """Pixel-level RMSE between two images.

    Requires examples to use mplvega.example_support.ExampleOutputs.
    When dimensions differ, the larger image is resized to match the smaller.
    """
    from PIL import Image
    import numpy as np

    img_a_pil = Image.open(path_a).convert("RGB")
    img_b_pil = Image.open(path_b).convert("RGB")

    if img_a_pil.size != img_b_pil.size:
        print(
            f"  note: size mismatch {path_a.name} {img_a_pil.size} vs "
            f"{path_b.name} {img_b_pil.size}, resizing",
            file=sys.stderr,
        )
        target = (min(img_a_pil.width, img_b_pil.width),
                  min(img_a_pil.height, img_b_pil.height))
        img_a_pil = img_a_pil.resize(target, Image.LANCZOS)
        img_b_pil = img_b_pil.resize(target, Image.LANCZOS)

    a = np.asarray(img_a_pil, dtype=float)
    b = np.asarray(img_b_pil, dtype=float)

    mse = float(np.mean((a - b) ** 2))
    return math.sqrt(mse)


def print_table(results: list[dict[str, Any]]) -> None:
    print()
    print(f"{'Example':<30} {'MPL vs FP(mpl)':>15} {'Vega vs FP(vl)':>15}")
    print("-" * 62)
    for row in results:
        mpl_score = row.get("mpl_vs_fortplot_mpl")
        vega_score = row.get("vega_vs_fortplot_vega")
        mpl_str = f"{mpl_score:.2f}" if mpl_score is not None else "N/A"
        vega_str = f"{vega_score:.2f}" if vega_score is not None else "N/A"
        print(f"{row['example']:<30} {mpl_str:>15} {vega_str:>15}")
    print()


def check_threshold(results: list[dict[str, Any]], threshold: float) -> None:
    failures = []
    for row in results:
        for key in ("mpl_vs_fortplot_mpl", "vega_vs_fortplot_vega"):
            score = row.get(key)
            if score is not None and score > threshold:
                failures.append(f"{row['example']}/{key}: {score:.2f}")
    if failures:
        print(f"FAIL: {len(failures)} example(s) exceed RMSE threshold {threshold}:")
        for f in failures:
            print(f"  {f}")
        sys.exit(1)
    else:
        print(f"PASS: all examples within RMSE threshold {threshold}")


if __name__ == "__main__":
    main()
